### ISSUE TITLE
Fetch feeds failed - object does not exist...

### ISSUE THREAD

**Issue by matesicsimun** [chenjr0719/Facebook-Page-Crawler#11]
Hello,

It seems as though the crawler does not work any more. It presents with an exception "Fetch feeds failed", and I've noticed that in the log there is a message saying "Object does not exist, cannot be loaded due to missing permission or reviewable feature...".

I've tried multiple URLs, as well as passing my own AppId - which also produces a "Fetch feeds failed" exception but does not produce the "Object does not exist..." message.

Is this a fault of mine, or did the changes in the Graph API disable the crawler?

EDIT:
I am aware of the changes brought on by Facebook regarding the Graph API and I have gotten a valid access token, or rather an app id and app secret.

**Comment by daph-td** [comment]
Hi @matesicsimun! I'm new to Graph API. I followed the exact instructions and when I run the command `facebook_page_crawler $app_id $app_secret $targets $since $until` to run the code, I encountered the error "Fetch feeds failed". 

I was wondering: 
1. Do I need to modify anything inside the source code to adjust to my case?
2. What does $target refer to, is it a keyword we put into search, or ID, or ?

Thank you in advanced if you can help with this!

**Comment by matesicsimun** [comment]
Hello, @daph-td! 

I believe the changes made to Graph API are such that this code cannot run anymore. 
If you are interested in something such as parsing comments from news sites, perhaps you can contact me by email so I can explain an alternate solution.
